[build]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  publish = "build"


[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--force"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff" 